### ISSUE TITLE
Contour Ingress does not rewrite path in Path mode

### ISSUE THREAD

**Issue by paulxuca** [Octops/gameserver-ingress-controller#35]
Hi there!

We are seeing an issue where using the contour router does not rewrite request paths without the assigned game server prefix (i.e `/game-server-prefix/path-to-get` does not get rewritten to just `/path-to-get` when hitting the game server pod). AFAIK nginx ingress does support it.

Anyway we can get the same behaviour with contour ingress?

**Comment by danieloliveira079** [comment]
@paulxuca could you please give me a bit more information about your setup? 

I think the contour only does rewrite if you use https://projectcontour.io/docs/v1.21.0/config/request-rewriting/.

The Octops Controller is not using the HTTPProxy resource. It only generates the Ingress and annotations.

For your information, you can use the template to inject the game server name wherever you need in the manifest.
https://github.com/Octops/gameserver-ingress-controller#path

**Comment by danieloliveira079** [comment]
Closing due to the lack of activity.
