### ISSUE TITLE
Dont require octops.io/issuer-tls-name annotation if octops.io/secret-name is present

### ISSUE THREAD

**Issue by jordo** [Octops/gameserver-ingress-controller#39]
```
failed to create ingress for gameserver tankkings-production-fleet-szpbt-949jw: annotation octops.io/issuer-tls-name for tankkings-production-fleet-szpbt-949jw must be present, check your Fleet or GameServer manifest."
```

Do we need `octops.io/issuer-tls-name` if `octops.io/secret-name` is specified?

**Comment by jordo** [comment]
My mistake, may be refactored to `tls-secret-name`.  Will confirm and close if this issue is N/A

**Comment by danieloliveira079** [comment]
The `octops.io/issuer-tls-name` can be ignored if you are providing your own TLS.

If you have your own Cert and it is stored in a Secret, the `octops.io/secret-name` is the name of that secret. That will tell the Ingress controller where to look for the Cert.

**Comment by jordo** [comment]
It looks like it's been changed from `secret-name` to `tls-secret-name`.  Will confirm shortly...

**Comment by jordo** [comment]
OK, so this is still an issue.  Here's is latest output, with the `tls-secret-name` annotation:

```
time="2022-09-12T20:08:11Z" level=error msg="failed to reconcile ingress default/asteroids-staging-fleet-f64qw-7m5q4: failed to create ingress for gameserver asteroids-staging-fleet-f64qw-7m5q4: annotation octops.io/issuer-tls-name for asteroids-staging-fleet-f64qw-7m5q4 must be present, check your Fleet or GameServer manifest." component=event_handler
time="2022-09-12T20:08:11Z" level=info msg="skipping default/tankkings-production-fleet-dvcff-2dvmm, annotation octops.io/gameserver-ingress-mode not present" component=event_handler event=updated
time="2022-09-12T20:08:11Z" level=error msg="failed to reconcile ingress default/asteroids-staging-fleet-f64qw-8xwrl: failed to create ingress for gameserver asteroids-staging-fleet-f64qw-8xwrl: annotation octops.io/issuer-tls-name for asteroids-staging-fleet-f64qw-8xwrl must be present, check your Fleet or GameServer manifest." component=event_handler
```
And, annotations that are on the gameserver:

<img width="1164" alt="Screen Shot 2022-09-12 at 2 10 54 PM" src="https://user-images.githubusercontent.com/323868/189748692-aba92107-6481-4d23-8036-60257a3e2411.png">

So the gameserver does have the `tls-secret-name` annotation, but it seems the controller still wants `octops.io/issuer-tls-name` to be specified.

**Comment by jordo** [comment]
I guess looking through the code, I just shouldn't set the `terminate-tls` annotation...  That flag itself looks kind of superfluous as it just then sets OctopsAnnotationIssuerName on the ingress certmanager annotations.  

In which case, maybe it could be just removed alltogether?

https://github.com/Octops/gameserver-ingress-controller/blob/6cd6689be130fd2f31a0d5979c4cce8e03b12239/pkg/reconcilers/options.go#L162-L182

**Comment by danieloliveira079** [comment]
From the README: https://github.com/Octops/gameserver-ingress-controller#wildcard-certificates
Does that work for you?

```
2. Provide a self-managed wildcard certificate.
- Add a [TLS secret](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) to the default namespace that holds the wildcard certificate content. That certificate must have been generated, acquired or bought from a different source.
- Set the annotation octops.io/terminate-tls: "false". That will tell CertManager to ignore that Fleet.
- Add the annotation octops.io/tls-secret-name: "my-wildcard-cert". That secret will be added to the Ingress under the TLS section. It will tell Envoy to use that secret content to terminate TLS for the public game server endpoint.
```

**Comment by jordo** [comment]
Yes, omitting `octops.io/terminate-tls` the annotation or setting it to false works.
