### ISSUE TITLE
Getting some error logs about event permissions

### ISSUE THREAD

**Issue by jordo** [Octops/gameserver-ingress-controller#41]
```
events "tankkings-production-fleet-szpbt-lds6d.171434fc5f66ed97" is forbidden: User "system:serviceaccount:octops-system:octops" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
 'events "tankkings-production-fleet-szpbt-lds6d.171434fc5f66ed97" is forbidden: User "system:serviceaccount:octops-system:octops" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
```

octops controller is installed in standard octops-system namespace, via install.yaml.  the fleet is in default namespace.

**Comment by danieloliveira079** [comment]
Can you please confirm you have installed the latest version of the RBAC required by octops?
https://github.com/Octops/gameserver-ingress-controller/blob/main/deploy/install.yaml#L15

The lines below are required.

```
  - apiGroups: ["agones.dev"]
    resources: ["gameservers","fleets"]
    verbs: ["get", "update", "list", "watch"]
```

**Comment by jordo** [comment]
Looks correct?  

<img width="1033" alt="Screen Shot 2022-09-12 at 11 35 03 PM" src="https://user-images.githubusercontent.com/323868/189817494-3b18430d-4c9f-446d-9ddd-5d42f031e363.png">

**Comment by danieloliveira079** [comment]
According to the error you posted it is possible that we have to add "update" to the RBAC. However I am curious when this event is actually happening. The controller is not updating events but only creating.

```
- apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "update" ]
```

**Comment by jordo** [comment]
> According to the error you posted it is possible that we have to add "update" to the RBAC.

Thats how i interpretted that as well, but I didn't understand why the controller would want to update and event.  I can provide the full controller logs if that helps

**Comment by danieloliveira079** [comment]
Yes that may help me understand what is going on.

**Comment by jordo** [comment]
OK, will try and provide tomorrow as I'll have to search back through.  The logs look clean now that I fixed our tls annotation issue, so I don't see the error in the current controller logs.

**Comment by danieloliveira079** [comment]
Tks I will close this issue.
