### ISSUE TITLE
Support multiple hosts

### ISSUE THREAD

**Issue by kimxogus** [Octops/gameserver-ingress-controller#43]
I need 2 hosts, one for internal ingress and the other for external ingress(end users) usage, but it seems that only 1 host is supported in octops ingress controller.

Can you add this feature? Splitting fqdn annotation by `,` character could be simple.

**Comment by danieloliveira079** [comment]
Tks @kimxogus for suggesting this feature. I will evaluate how this affects the current implementation.

**Comment by danieloliveira079** [comment]
Alternatively, if you want to access the game server within the network you can use the **Service** that the gameserver-controller creates. A gameserver named `octops-domain-tqmvm-rcl5p` can be accessed using the FQDN `octops-domain-tqmvm-rcl5p.default.svc.cluster.local`. Assuming your game servers are running under the default namespace.

More information about that on https://kubernetes.io/docs/concepts/services-networking/dns-pod-service

The address `octops-domain-tqmvm-rcl5p.default.svc.cluster.local` can be accessed from any pod running within the cluster. Including pods running in a different namespace.

**Comment by danieloliveira079** [comment]
Closing this issue since the internal name can be used for Pod to Pod communication.

**Comment by jongwow** [comment]
This feature could be useful when supporting multiple hosts for external ingress(end users). can you reconsider it?

**Comment by danieloliveira079** [comment]
Yes I believe I can. One question I would have about how TLS would be configured for these cases. I am reopening the issue and will look more into that this weekend. Tks for the feedback.

**Comment by danieloliveira079** [comment]
@jongwow Please test the support to multiple host using the image `octops/gameserver-ingress-controller:0.2.4`.

Also check this PR to understand how the Fleet or GameServer annotations should be.
https://github.com/Octops/gameserver-ingress-controller/pull/45

Let me know if that works or if you got any bug or feedback. I will park the development until I here something back from you.

**Comment by jongwow** [comment]
Thank you for your work! Actually I don't know much about TLS configuration because my colleague handles it and can't access due to security issues. All I know is that when using external proxy, it needs two hosts.

I really appreciate your work and I will let you know after check it :)

**Comment by danieloliveira079** [comment]
PR merged and feature available.
