### ISSUE TITLE
arm64 support?

### ISSUE THREAD

**Issue by gotchipete** [Octops/gameserver-ingress-controller#51]
pretty please? :D

**Comment by danieloliveira079** [comment]
@gotchipete could you please test the tag 0.2.6? I recently pushed the ARM version.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/4673760/225980903-2aa2db86-a11a-4d5a-aa6f-2ec3703bc66f.png">

**Comment by gotchipete** [comment]
Will do today sir!

**Comment by gotchipete** [comment]
works great!

**Comment by danieloliveira079** [comment]
Perfect I will open a PR that will make ARM builds default too.
