### ISSUE TITLE
Ingress created by the controller is unreachable

### ISSUE THREAD

**Issue by paulxuca** [Octops/gameserver-ingress-controller#55]
The controller has created an ingress that looks like:
```
NAME                        CLASS    HOSTS                           ADDRESS          PORTS     AGE
some-name-9d572   <none>   someaddress.com   104.196.xxx.xx   80, 443   34m
```

I've ensured that the game server is running correctly but there is nothing running at the address specified by the ingress. Any suggestions on how I might be able to debug this issue? 

Thanks in advance!

**Comment by eddie-knight** [comment]
Just another user chiming in here... Sorry to hear about the weird behavior. Perhaps this article will help by walking you through a few common debugging steps? If nothing else it'll add some more data points to rule out common issues.

https://medium.com/@ManagedKube/kubernetes-troubleshooting-ingress-and-services-traffic-flows-547ea867b120

**Comment by danieloliveira079** [comment]
Hey @paulxuca this address is usually the IP of the load balancer. Additionally to the link Eddie shared you can check https://kubernetes.io/docs/concepts/services-networking/ingress/#types-of-ingress.

What do you see when you run `kubectl -n $NAMESPACE get svc`? The NAMESPACE should be the namespace where you are running your ingress controller responsible for routing traffic.

**Comment by danieloliveira079** [comment]
How are you provisioning certificates for TLS?

**Comment by danieloliveira079** [comment]
>Testing connectivity by trying to dig/ nslookup the HOST issued (as well as directly trying to access the underlying IP address)
Trying to connect using the IP will not work. The ingress will only route traffic based on the host name. That is also important for TLS/HTTPS.

**Comment by danieloliveira079** [comment]
No worries. Would you mind sharing more details about what fixed the problem. That way we can help others from the community. Thank you.
