### ISSUE TITLE
tls-secret-name requires terminate-tls=true, which makes the cert-issuer override that certificate in kubernetes

### ISSUE THREAD

**Issue by playpals-studio** [Octops/gameserver-ingress-controller#56]
Hello,
I can't set the tls-secret-name without setting terminate-tls to "true".
The problem is, when I set the terminate-tls to "true" cert-manager will try to make a cert with same name as written in tls-secret-name, and will manage the cert that was supposed to be made manually or imported from different source.

After inspecting the go code, the problem seems to be that setting "terminate-tls" to true will activate both "tls-secret-name" and "issuer-tls-name".

Since WithTLSCertIssuer runs after WithTLS, could you please add a check in WithTLSCertIssuer if there is TLS fields, to avoid invoking the CertIssuer and overriding the certificate ?

Thank you for the cool repo btw :D

**Comment by danieloliveira079** [comment]
Hello @playpals-studio,

Thank you for opening this issue.

What is your end goal? Having a Cert provisioned by other means but making it part of the Ingress TLS section?

**Comment by danieloliveira079** [comment]
@playpals-studio could you please try again using the following image name?
`octops/gameserver-ingress-controller:0.2.8-dev`

I've pushed a fix and tested locally. It seems to be working. As soon as you confirm that I can merge the PR and push the final image to Docker Hub.

**Comment by danieloliveira079** [comment]
@playpals-studio did you have the chance to try this version. I would like to close the issue or merge the PR. tks

**Comment by jordo** [comment]
Hey there daniel.  We have a platform that we are are deploying this fix to...  Coincidentally, we ran into the same problem.    We DONT want the `"cert-manager.io/cluster-issuer"` annotation on the ingress, but DO want `octops.io/terminate-tls: "true"` and want to specify our own `octops.io/tls-secret-name`.  Currently `WithTLSCertIssuer` requires this if `terminateTLS` ends up being true.  

The fix here: https://github.com/Octops/gameserver-ingress-controller/pull/57/files looks correct.  Will try and test with `octops/gameserver-ingress-controller:0.2.8-dev`

**Comment by danieloliveira079** [comment]
Tks @jordo, please let me know how that goes and I can publish a new release.

**Comment by jordo** [comment]
Just tested in a live cluster with `octops/gameserver-ingress-controller:0.2.8-dev` and the ingress resource annotions are correct now with those options.

**Comment by danieloliveira079** [comment]
Fix available on release 0.2.9.
