### ISSUE TITLE
Pass custom labels and/or annotations upon creation to  gameserver-ingress-controller managed ingresses

### ISSUE THREAD

**Issue by jordo** [Octops/gameserver-ingress-controller#7]
It would be nice to be able to potentially pass (static) labels or annotations through to the ingress objects that are created and managed under gameserver-ingress-controller. 

For example, perhaps annotating our fleet with:  
`octops-custom-annotation-our-annotation: something-cool` ends up getting stripped and applying `our-annotation: something-cool` to Ingress objects.  We can then use this to annotate these Ingress objects with say external-dns which can handle our root dns record/entry for all gameservers.

**Comment by danieloliveira079** [comment]
That is a great request. Sounds like I could start by adding support for annotations only. On a second step I can add support for labels.

**Comment by danieloliveira079** [comment]
This feature has been implemented and is part of the v0.1.3 release.
